language: python
sudo: false
python:
- 3.5
- 3.6
cache: pip
install:
- pip install -e .[test]
script:
- py.test --cov=aiodataloader
after_success:
- coveralls
matrix:
  fast_finish: true
  include:
  - python: '3.5'
    install: pip install flake8
    script: flake8
  - python: '3.5'
    script: |
      pip install mypy
      mypy aiodataloader.py  --check-untyped-defs  --ignore-missing-imports
